const inProduction = process.env.NODE_ENV === 'production';

module.exports = {
    parserOptions: {
        ecmaVersion: 8,
        ecmaFeatures: {
            experimentalObjectRestSpread: true,
            jsx: true,
        },
        sourceType: 'module',
    },

    env: {
        es6: true,
        node: true,
    },

    plugins: [
        'standard',
        'promise',
        'html',
        'import',
    ],

    globals: {
        document: false,
        navigator: false,
        window: false,
    },

    settings: {
        'import/resolver': {
            node: {
                extensions: ['.js', '.json']
            }
        },
        'import/extensions': [
            '.js',
            '.vue',
        ],
        'import/ignore': [
            'node_modules',
            '\\.(0e|scss|css|less|hbs|svg|json)$',
        ],
    },

    rules: {
        // == Possible Errors
        'no-cond-assign': [2, 'always'],
        'no-console': inProduction ? 2 : 0,
        'no-constant-condition': [2, { 'checkLoops': false }],
        'no-control-regex': 2,
        'no-debugger': inProduction ? 2 : 0,
        'no-dupe-args': 2,
        'no-dupe-keys': 2,
        'no-duplicate-case': 2,
        'no-empty': 2,
        'no-empty-character-class': 2,
        'no-ex-assign': 2,
        'no-extra-boolean-cast': 2,
        'no-extra-parens': [2, 'functions'],
        'no-extra-semi': 2,
        'no-func-assign': 2,
        'no-inner-declarations': [2, 'functions'],
        'no-invalid-regexp': 2,
        'no-irregular-whitespace': 2,
        'no-obj-calls': 2,
        'no-prototype-builtins': 2,
        'no-regex-spaces': 2,
        'no-sparse-arrays': 2,
        'no-template-curly-in-string': 2,
        'no-unexpected-multiline': 2,
        'no-unreachable': 2,
        'no-unsafe-finally': 2,
        'no-unsafe-negation': 2,
        'use-isnan': 2,
        'valid-jsdoc': 2,
        'valid-typeof': 2,
        // == Best Practices
        'accessor-pairs': 2,
        'array-callback-return': 2,
        'block-scoped-var': 0,
        'class-methods-use-this': 2,
        'complexity': [2, { 'max': 20 }],
        'consistent-return': 2,
        'curly': [2, 'multi-line', 'consistent'],
        'default-case': 2,
        'dot-location': [2, 'property'],
        'dot-notation': [2, { allowKeywords: false }],
        'eqeqeq': [2, 'allow-null'],
        'guard-for-in': 2,
        'no-alert': inProduction ? 2 : 0,
        'no-caller': 2,
        'no-case-declarations': 0,
        'no-div-regex': 0,
        'no-else-return': 2,
        'no-empty-function': 2,
        'no-empty-pattern': 2,
        'no-eq-null': 2,
        'no-eval': 2,
        'no-extend-native': 2,
        'no-extra-bind': 2,
        'no-labels': [2, { 'allowLoop': false, 'allowSwitch': false }],
        'no-fallthrough': 2,
        'no-floating-decimal': 2,
        'no-global-assign': [2, { exceptions: [] }],
        'no-implicit-coercion': [0, {
            boolean: false,
            number: true,
            string: true,
            allow: [],
        }],
        'no-implicit-globals': 0,
        'no-implied-eval': 2,
        'no-invalid-this': 2,
        'no-iterator': 2,
        'no-lone-blocks': 2,
        'no-loop-func': 2,
        'no-magic-numbers': [0, {
            ignore: [1],
            ignoreArrayIndexes: true,
            enforceConst: true,
            detectObjects: false,
        }],
        'no-multi-spaces': 2,
        'no-multi-str': 2,
        'no-new-func': 2,
        'no-new-wrappers': 2,
        'no-new': 0,
        'no-octal-escape': 2,
        'no-octal': 2,
        'no-param-reassign': [2, { 'props': false }],
        'no-proto': 2,
        'no-redeclare': 2,
        'no-return-assign': [2, 'except-parens'],
        'no-script-url': 2,
        'no-self-assign': 2,
        'no-self-compare': 2,
        'no-sequences': 2,
        'no-throw-literal': 2,
        'no-unmodified-loop-condition': 2,
        'no-unused-expressions': [2, {
            allowShortCircuit: true,
            allowTernary: true,
        }],
        'no-useless-call': 2,
        'no-useless-concat': 2,
        'no-useless-escape': 2,
        'no-useless-return': 2,
        'no-void': 2,
        'no-warning-comments': [0, { terms: ['todo', 'fixme', 'xxx'], location: 'start' }],
        'no-with': 2,
        'radix': 2,
        'vars-on-top': 0,
        'wrap-iife': [2, 'outside'],
        'yoda': [2, 'never'],
        // == Strict Mode
        strict: [2, 'never'],
        // == Variables
        'init-declarations': 0,
        'no-catch-shadow': 0,
        'no-delete-var': 2,
        'no-restricted-globals': 0,
        'no-shadow-restricted-names': 2,
        'no-shadow': 2,
        'no-undef-init': 2,
        'no-undef': 2,
        'no-undefined': 0,
        'no-unused-vars': [2, { vars: 'local', args: 'after-used' }],
        'no-use-before-define': 2,
        // == Node.js and CommonJS
        'callback-return': 0,
        'global-require': 0,
        'handle-callback-err': 0,
        'no-mixed-requires': [0, false],
        'no-new-require': 2,
        'no-path-concat': 2,
        'no-process-env': 0,
        'no-process-exit': 2,
        'no-restricted-modules': 0,
        'no-sync': 0,
        // == Stylistic Issues
        'array-bracket-spacing': [2, 'never'],
        'block-spacing': [2, 'always'],
        'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
        'camelcase': [2, { 'properties': 'never' }],
        'comma-dangle': [2, 'always-multiline'],
        'comma-spacing': [2, { 'before': false, 'after': true }],
        'comma-style': [2, 'last'],
        'computed-property-spacing': [2, 'never'],
        'consistent-this': 0,
        'eol-last': 2,
        'func-call-spacing': [2, 'never'],
        'func-name-matching': 2,
        'func-names': [2, 'never'],
        'func-style': 0,
        'id-blacklist': 0,
        'id-length': 0,
        'id-match': 0,
        'indent': [2, 4, { 'SwitchCase': 1, VariableDeclarator: 1, outerIIFEBody: 1 }],
        'jsx-quotes': [0, 'prefer-double'],
        'key-spacing': [2, { 'beforeColon': false, 'afterColon': true }],
        'keyword-spacing': [2, {
            before: true,
            after: true,
            overrides: {
                if: { after: false },
                while: { after: false },
                return: { after: true },
                throw: { after: true },
                switch: { after: false },
                case: { after: true },
            },
        }],
        'lines-around-comment': 0,
        'linebreak-style': [2, 'unix'],
        'lines-around-directive': [2, 'always'],
        'max-depth': [0, 4],
        'max-len': [2, 100, 2, {
            ignoreUrls: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
            ignoreRegExpLiterals: true,
            ignoreComments: false
        }],
        'max-lines': [0, {
            max: 300,
            skipBlankLines: true,
            skipComments: true
        }],
        'max-nested-callbacks': 0,
        'max-params': [0, 3],
        'max-statements': [0, 10],
        'max-statements-per-line': [0, { max: 1 }],
        'multiline-ternary': 0,
        'new-cap': [2, { 'newIsCap': true, 'capIsNew': false }],
        'new-parens': 2,
        'newline-after-var': 2,
        'newline-before-return': 2,
        'newline-per-chained-call': [2, { ignoreChainWithDepth: 4 }],
        'no-array-constructor': 2,
        'no-bitwise': 0,
        'no-continue': 2,
        'no-inline-comments': 0,
        'no-lonely-if': 2,
        'no-mixed-operators': [0, {
            groups: [
                ['+', '-', ],
                ['*', '/', '%', '**'],
                ['&', '|', '^', '~', '<<', '>>', '>>>'],
                ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
                ['&&', '||'],
                ['in', 'instanceof']
            ],
            allowSamePrecedence: false
        }],
        'no-mixed-spaces-and-tabs': 2,
        'no-multiple-empty-lines': [2, { 'max': 1 }],
        'no-negated-condition': 0,
        'no-nested-ternary': 2,
        'no-new-object': 2,
        'no-plusplus': 0,
        'no-restricted-syntax': [
            2,
            'DebuggerStatement',
            'ForInStatement',
            'LabeledStatement',
            'WithStatement',
        ],
        'no-tabs': 2,
        'no-ternary': 0,
        'no-trailing-spaces': 2,
        'no-underscore-dangle': [1, { allowAfterThis: true, allowAfterSuper: true }],
        'no-unneeded-ternary': [2, { 'defaultAssignment': false }],
        'no-whitespace-before-property': 2,
        'object-curly-newline': [0, {
            ObjectExpression: { minProperties: 0, multiline: true },
            ObjectPattern: { minProperties: 0, multiline: true }
        }],
        'object-curly-spacing': [2, 'always'],
        'object-property-newline': [2, { 'allowMultiplePropertiesPerLine': true }],
        'one-var-declaration-per-line': [2, 'always'],
        'one-var': [0],
        'operator-assignment': [2, 'always'],
        'operator-linebreak': [2, 'after', {
            'overrides': {
                '?': 'before',
                ':': 'before',
                '>=': 'before',
                '===': 'before',
                '-': 'before',
                '+': 'before',
            },
        }],
        'padded-blocks': [2, 'never'],
        'quote-props': [2, 'as-needed', { keywords: false, unnecessary: true, numbers: false }],
        'quotes': [2, 'single', { 'avoidEscape': true, 'allowTemplateLiterals': true }],
        'require-jsdoc': 0,
        'semi': [2, 'always'],
        'semi-spacing': [2, { 'before': false, 'after': true }],
        'sort-keys': [0, 'asc', { caseSensitive: false, natural: true }],
        'sort-vars': 0,
        'space-before-blocks': [2, 'always'],
        'space-in-parens': [2, 'never'],
        'space-infix-ops': 2,
        'space-unary-ops': [2, { 'words': true, 'nonwords': false }],
        'spaced-comment': [2, 'always', { 'line': { 'markers': ['*package', '!', ','] }, 'block': { 'balanced': true, 'markers': ['*package', '!', ','], 'exceptions': ['*'] } }],
        'unicode-bom': [2, 'never'],
        // == ECMAScript 6
        'arrow-body-style': [2, 'as-needed', { 'requireReturnForObjectLiteral': true }],
        'arrow-parens': [2, 'as-needed', { 'requireForBlockBody': false }],
        'arrow-spacing': [2, { 'before': true, 'after': true }],
        'constructor-super': 2,
        'generator-star-spacing': [2, { before: false, after: true }],
        'no-class-assign': 2,
        'no-confusing-arrow': [2, {
            allowParens: false,
        }],
        'no-const-assign': 2,
        'no-dupe-class-members': 2,
        'no-duplicate-imports': 2,
        'no-new-symbol': 2,
        'no-restricted-imports': 0,
        'no-this-before-super': 2,
        'no-useless-computed-key': 2,
        'no-useless-constructor': 2,
        'no-useless-rename': 2,
        'no-var': 2,
        'object-shorthand': [2, 'always', {
            ignoreConstructors: false,
            avoidQuotes: true,
        }],
        'prefer-arrow-callback': [2, {
            allowNamedFunctions: false,
            allowUnboundThis: true,
        }],
        'prefer-const': [0, {
            destructuring: 'any',
            ignoreReadBeforeAssign: true,
        }],
        'prefer-numeric-literals': 0,
        'prefer-rest-params': 2,
        'prefer-spread': 0,
        'prefer-template': 2,
        'require-yield': 2,
        'rest-spread-spacing': [2, 'never'],
        'sort-imports': [0, {
            ignoreCase: false,
            ignoreMemberSort: false,
            memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
        }],
        'symbol-description': 2,
        'template-curly-spacing': [2, 'never'],
        'yield-star-spacing': [2, 'after'],

        // == Standard plugin

        'standard/object-curly-even-spacing': [2, 'either'],
        'standard/array-bracket-even-spacing': [2, 'either'],
        'standard/computed-property-even-spacing': [2, 'even'],

        // == Promise plugin

        'promise/param-names': 2,

        // == Import plugin
        'import/first': [2],
        'import/no-duplicates': [2],
        'import/order': [2, {'groups': ['builtin', 'external',  'index', 'sibling', 'internal', 'parent']}],
        'import/newline-after-import': [2],
        'import/no-amd': [2],
        'import/no-commonjs': [2],
        'import/no-extraneous-dependencies': [2, {'devDependencies': false, 'optionalDependencies': false, 'peerDependencies': false}],
    },
};

